### ISSUE TITLE
Circular import

### ISSUE THREAD

**Issue by maxdebayser** [franzinc/agraph-python#4]
There is a circular import in query.py because it transitively imports franz.openrdf.repository.repository which in turn imports query

To test (with python2) just run this single line:

#> from franz.openrdf.query.query import QueryLanguage

and you will get:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from franz.openrdf.query.query import QueryLanguage
  File "/home/mbayser/.pyenv/versions/agraph_test/lib/python2.7/site-packages/agraph_python-100.0.0.dev0-py2.7.egg/franz/openrdf/query/query.py", line 21, in <module>
    from .queryresult import GraphQueryResult, TupleQueryResult
  File "/home/mbayser/.pyenv/versions/agraph_test/lib/python2.7/site-packages/agraph_python-100.0.0.dev0-py2.7.egg/franz/openrdf/query/queryresult.py", line 15, in <module>
    from ..repository.repositoryresult import RepositoryResult
  File "/home/mbayser/.pyenv/versions/agraph_test/lib/python2.7/site-packages/agraph_python-100.0.0.dev0-py2.7.egg/franz/openrdf/repository/__init__.py", line 10, in <module>
    from .repository import Repository
  File "/home/mbayser/.pyenv/versions/agraph_test/lib/python2.7/site-packages/agraph_python-100.0.0.dev0-py2.7.egg/franz/openrdf/repository/repository.py", line 22, in <module>
    from .repositoryconnection import RepositoryConnection
  File "/home/mbayser/.pyenv/versions/agraph_test/lib/python2.7/site-packages/agraph_python-100.0.0.dev0-py2.7.egg/franz/openrdf/repository/repositoryconnection.py", line 24, in <module>
    from ..query.query import Query, TupleQuery, UpdateQuery, GraphQuery, BooleanQuery, QueryLanguage

To workaround, one only needs to import repository first:

import franz.openrdf.repository.repository
from franz.openrdf.query.query import QueryLanguage

**Comment by franzinc** [comment]
Thanks, @maxdebayser for bringing this to our attention.
